#!/usr/bin/env ansible-playbook

# Usage: ansible-playbook -v -i inventory.ini -l local minecraft.yml

- name: "Install minecraft server"
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - minecraft
